version: "3"

networks:
  stack_ponte:
    external: true

services:
  apachealvitre:
    container_name: "apachealvitre"
    image: webdevops/apache
    networks:
      - stack_ponte
    restart: always
    ports:
      - 851:80
    volumes:
      - "${PATH}/oal:/app"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sitealvitre.rule=Host(`www.${DOMAIN}`,`${DOMAIN}`, `oalconta.com`, `www.oalconta.com`)"
      - "traefik.http.services.sitealvitre.loadbalancer.server.port=80"
